version: '0.1'
services:
  dhcp_wh_service:
    image: ghcr.io/wessrow/dhcp_provision:latest
    container_name: dhcp_wh
    ports:
      - "443:5005"
    networks:
    - netbox-docker_default
    volumes:
      - tftp-data:/tftpboot
    env_file:
      - dhcp_wh_service.env
  tftp-server:
    image: ghcr.io/wessrow/tftp:latest
    container_name: tftp
    entrypoint: in.tftpd
    command: -L -4 --secure --address 0.0.0.0:69 --verbosity 3 /tftpboot
    ports:
      - "0.0.0.0:69:69/udp"
    volumes:
      - tftp-data:/tftpboot
    restart: unless-stopped

volumes:
  tftp-data:

networks:
  netbox-docker_default:
    external: true