name: Build and Push Docker Image

on:
  release:
    types: [created]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry (GHCR)
        if: success()
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Extract release tag
        id: get_tag
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build and tag Docker image
        run: |
          docker build -t ghcr.io/wessrow/dhcp_provision:${{ env.TAG }} .
          docker tag ghcr.io/wessrow/dhcp_provision:${{ env.TAG }} ghcr.io/wessrow/dhcp_provision:latest

      - name: Push Docker image to GHCR
        run: |
          docker push ghcr.io/wessrow/dhcp_provision:${{ env.TAG }}
          docker push ghcr.io/wessrow/dhcp_provision:latest